name: Notes App Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # or any other Python version you prefer

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements file for dependencies

    - name: Run tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s tests -p "*.py"  # Assuming your tests are in a 'tests' folder
